services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    ports:
      - 5800:5800
    volumes:
      - /mnt/dietpi_userdata/handbrake:/config:rw
      - /mnt/recordings:/storage:rw
      - /mnt/dietpi_userdata/Medias/Tele:/output:rw
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
